website:
    resource: "@WebsiteBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

blog:
    resource: "@BlogBundle/Controller/"
    prefix:   /
    type: annotation

product:
    resource: '@ProductBundle/Controller/'
    prefix:   /
    type: annotation
